name: variance_dart
description: An Account Abstraction (4337) Development kit, for quickly building mobile web3 apps and smart wallets.
version: 0.1.3
documentation: https://docs.variance.space
homepage: https://variance.space
repository: https://github.com/vaariance/variance-dart
issue_tracker: https://github.com/vaariance/variance-dart/issues

environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=3.13.0"

platforms:
  android:
  ios:
  windows:

dependencies:
  flutter:
    sdk: flutter
  web3dart: ^2.7.3
  http: ^1.2.0
  web3_signers: ^0.0.14-alpha-01

dev_dependencies:
  web3dart_builders: ^0.1.2
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  mockito: ^5.4.2

topics:
  - wallets
  - ethereum
  - web3
  - account-abstraction
